#### Libaries

In [74]:
import pandas as pd

#### Dataset

In [30]:
#TODO: replace local link with github link so we users can work with code

#url = 'github_dataset_url'

#To be remove before being notebook is uploaded to github
data_path = r"C:\Users\ejiro\Documents\work_stuff\data\analysis\projects\personal_or_side_project\nyc_accident_analysis\raw\raw.csv" 

df = pd.read_csv(data_path)

In [31]:
df.head()

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,8/29/2020,15:40:00,BRONX,10466.0,40.89210,-73.833760,POINT (-73.83376 40.8921),PRATT AVENUE,STRANG AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4342908,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1,8/29/2020,21:00:00,BROOKLYN,11221.0,40.69050,-73.919914,POINT (-73.919914 40.6905),BUSHWICK AVENUE,PALMETTO STREET,NaN,...,Unspecified,NaN,NaN,NaN,4343555,Sedan,Sedan,NaN,NaN,NaN
2,8/29/2020,18:20:00,NaN,NaN,40.81650,-73.946556,POINT (-73.946556 40.8165),8 AVENUE,NaN,NaN,...,NaN,NaN,NaN,NaN,4343142,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
3,8/29/2020,0:00:00,BRONX,10459.0,40.82472,-73.892960,POINT (-73.89296 40.82472),NaN,NaN,1047 SIMPSON STREET,...,Unspecified,Unspecified,Unspecified,NaN,4343588,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Sedan,Motorcycle,NaN
4,8/29/2020,17:10:00,BROOKLYN,11203.0,40.64989,-73.933890,POINT (-73.93389 40.64989),NaN,NaN,4609 SNYDER AVENUE,...,Unspecified,NaN,NaN,NaN,4342953,Sedan,Sedan,NaN,NaN,NaN

##### Converting Columns to Snakecase

In [32]:
df.columns

Index(['CRASH DATE', 'CRASH TIME', 'BOROUGH', 'ZIP CODE', 'LATITUDE',
       'LONGITUDE', 'LOCATION', 'ON STREET NAME', 'CROSS STREET NAME',
       'OFF STREET NAME', 'NUMBER OF PERSONS INJURED',
       'NUMBER OF PERSONS KILLED', 'NUMBER OF PEDESTRIANS INJURED',
       'NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST INJURED',
       'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST INJURED',
       'NUMBER OF MOTORIST KILLED', 'CONTRIBUTING FACTOR VEHICLE 1',
       'CONTRIBUTING FACTOR VEHICLE 2', 'CONTRIBUTING FACTOR VEHICLE 3',
       'CONTRIBUTING FACTOR VEHICLE 4', 'CONTRIBUTING FACTOR VEHICLE 5',
       'COLLISION_ID', 'VEHICLE TYPE CODE 1', 'VEHICLE TYPE CODE 2',
       'VEHICLE TYPE CODE 3', 'VEHICLE TYPE CODE 4', 'VEHICLE TYPE CODE 5'],
      dtype='object')

In [33]:
columns = df.columns

In [34]:
columns = columns.str.strip()

In [35]:
columns

Index(['CRASH DATE', 'CRASH TIME', 'BOROUGH', 'ZIP CODE', 'LATITUDE',
       'LONGITUDE', 'LOCATION', 'ON STREET NAME', 'CROSS STREET NAME',
       'OFF STREET NAME', 'NUMBER OF PERSONS INJURED',
       'NUMBER OF PERSONS KILLED', 'NUMBER OF PEDESTRIANS INJURED',
       'NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST INJURED',
       'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST INJURED',
       'NUMBER OF MOTORIST KILLED', 'CONTRIBUTING FACTOR VEHICLE 1',
       'CONTRIBUTING FACTOR VEHICLE 2', 'CONTRIBUTING FACTOR VEHICLE 3',
       'CONTRIBUTING FACTOR VEHICLE 4', 'CONTRIBUTING FACTOR VEHICLE 5',
       'COLLISION_ID', 'VEHICLE TYPE CODE 1', 'VEHICLE TYPE CODE 2',
       'VEHICLE TYPE CODE 3', 'VEHICLE TYPE CODE 4', 'VEHICLE TYPE CODE 5'],
      dtype='object')

In [36]:
columns = columns.str.lower()

In [37]:
columns

Index(['crash date', 'crash time', 'borough', 'zip code', 'latitude',
       'longitude', 'location', 'on street name', 'cross street name',
       'off street name', 'number of persons injured',
       'number of persons killed', 'number of pedestrians injured',
       'number of pedestrians killed', 'number of cyclist injured',
       'number of cyclist killed', 'number of motorist injured',
       'number of motorist killed', 'contributing factor vehicle 1',
       'contributing factor vehicle 2', 'contributing factor vehicle 3',
       'contributing factor vehicle 4', 'contributing factor vehicle 5',
       'collision_id', 'vehicle type code 1', 'vehicle type code 2',
       'vehicle type code 3', 'vehicle type code 4', 'vehicle type code 5'],
      dtype='object')

In [38]:
columns = columns.str.replace(" ", "_")

In [39]:
columns

Index(['crash_date', 'crash_time', 'borough', 'zip_code', 'latitude',
       'longitude', 'location', 'on_street_name', 'cross_street_name',
       'off_street_name', 'number_of_persons_injured',
       'number_of_persons_killed', 'number_of_pedestrians_injured',
       'number_of_pedestrians_killed', 'number_of_cyclist_injured',
       'number_of_cyclist_killed', 'number_of_motorist_injured',
       'number_of_motorist_killed', 'contributing_factor_vehicle_1',
       'contributing_factor_vehicle_2', 'contributing_factor_vehicle_3',
       'contributing_factor_vehicle_4', 'contributing_factor_vehicle_5',
       'collision_id', 'vehicle_type_code_1', 'vehicle_type_code_2',
       'vehicle_type_code_3', 'vehicle_type_code_4', 'vehicle_type_code_5'],
      dtype='object')

In [40]:
df.columns = columns

In [41]:
df.columns

Index(['crash_date', 'crash_time', 'borough', 'zip_code', 'latitude',
       'longitude', 'location', 'on_street_name', 'cross_street_name',
       'off_street_name', 'number_of_persons_injured',
       'number_of_persons_killed', 'number_of_pedestrians_injured',
       'number_of_pedestrians_killed', 'number_of_cyclist_injured',
       'number_of_cyclist_killed', 'number_of_motorist_injured',
       'number_of_motorist_killed', 'contributing_factor_vehicle_1',
       'contributing_factor_vehicle_2', 'contributing_factor_vehicle_3',
       'contributing_factor_vehicle_4', 'contributing_factor_vehicle_5',
       'collision_id', 'vehicle_type_code_1', 'vehicle_type_code_2',
       'vehicle_type_code_3', 'vehicle_type_code_4', 'vehicle_type_code_5'],
      dtype='object')

In [42]:
df.dtypes

crash_date                        object
crash_time                        object
borough                           object
zip_code                         float64
latitude                         float64
longitude                        float64
location                          object
on_street_name                    object
cross_street_name                 object
off_street_name                   object
number_of_persons_injured          int64
number_of_persons_killed           int64
number_of_pedestrians_injured      int64
number_of_pedestrians_killed       int64
number_of_cyclist_injured          int64
number_of_cyclist_killed           int64
number_of_motorist_injured         int64
number_of_motorist_killed          int64
contributing_factor_vehicle_1     object
contributing_factor_vehicle_2     object
contributing_factor_vehicle_3     object
contributing_factor_vehicle_4     object
contributing_factor_vehicle_5     object
collision_id                       int64
vehicle_type_code_1               object
vehicle_type_code_2               object
vehicle_type_code_3               object
vehicle_type_code_4               object
vehicle_type_code_5               object
dtype: object

##### Convert crash_date and crash_time to datetime

In [43]:
df["crash_date"] = pd.to_datetime(df["crash_date"])

In [44]:
df["crash_time"] = pd.to_datetime(df["crash_time"].astype(str), format="%H:%M:%S")

In [45]:
df.dtypes

crash_date                       datetime64[ns]
crash_time                       datetime64[ns]
borough                                  object
zip_code                                float64
latitude                                float64
longitude                               float64
location                                 object
on_street_name                           object
cross_street_name                        object
off_street_name                          object
number_of_persons_injured                 int64
number_of_persons_killed                  int64
number_of_pedestrians_injured             int64
number_of_pedestrians_killed              int64
number_of_cyclist_injured                 int64
number_of_cyclist_killed                  int64
number_of_motorist_injured                int64
number_of_motorist_killed                 int64
contributing_factor_vehicle_1            object
contributing_factor_vehicle_2            object
contributing_factor_vehicle_3            object
contributing_factor_vehicle_4            object
contributing_factor_vehicle_5            object
collision_id                              int64
vehicle_type_code_1                      object
vehicle_type_code_2                      object
vehicle_type_code_3                      object
vehicle_type_code_4                      object
vehicle_type_code_5                      object
dtype: object

###### Extract Month and Day of the week from crash_date

In [47]:
df["month_of_crash"] = df["crash_date"].dt.strftime("%b")

In [48]:
df["day_of_crash"] = df["crash_date"].dt.day_name()

In [49]:
df["month_of_crash"].head()

0    Aug
1    Aug
2    Aug
3    Aug
4    Aug
Name: month_of_crash, dtype: object

In [50]:
df["day_of_crash"].head()

0    Saturday
1    Saturday
2    Saturday
3    Saturday
4    Saturday
Name: day_of_crash, dtype: object

###### Extract Hour from crash_time

In [51]:
df["hour_of_crash"] = df["crash_time"].dt.hour

In [52]:
df["hour_of_crash"].head()

0    15
1    21
2    18
3     0
4    17
Name: hour_of_crash, dtype: int32

###### Result

In [54]:
df[["crash_date", "crash_time", "day_of_crash", "month_of_crash", "hour_of_crash"]].sample(n=5)

,crash_date,crash_time,day_of_crash,month_of_crash,hour_of_crash
38287,2020-03-19,1900-01-01 12:45:00,Thursday,Mar,12
5042,2020-08-12,1900-01-01 16:00:00,Wednesday,Aug,16
45418,2020-03-03,1900-01-01 14:41:00,Tuesday,Mar,14
37699,2020-03-21,1900-01-01 18:15:00,Saturday,Mar,18
10773,2020-07-25,1900-01-01 20:00:00,Saturday,Jul,20

##### Cleaning Street Name

In [63]:
pd.reset_option("^display")

In [64]:
# I check mannually and the street name was formatted properly but to be safe I decided to go ahead and just do a quick clean up

In [65]:
df["street_of_crash"] = (
        df["on_street_name"].astype(str).str.strip().str.upper()
    )

In [67]:
df["street_of_crash"].sample(n=5)

30081       150 STREET
2322         93 AVENUE
71288         3 AVENUE
32385        FDR DRIVE
50505    NEREID AVENUE
Name: street_of_crash, dtype: object

##### create is_fatal column and populate with bool derived from number_of_persons_killed column

In [68]:
df['is_fatal'] = df['number_of_persons_killed'] > 0

In [69]:
df['is_fatal'].sample(n=5)

30115    False
53306    False
31379    False
5677     False
14766    False
Name: is_fatal, dtype: bool

##### Result (Cleaned Data)

In [72]:
df.sample(n=5)

,crash_date,crash_time,borough,zip_code,latitude,longitude,location,on_street_name,cross_street_name,off_street_name,...,vehicle_type_code_1,vehicle_type_code_2,vehicle_type_code_3,vehicle_type_code_4,vehicle_type_code_5,month_of_crash,day_of_crash,hour_of_crash,street_of_crash,is_fatal
65286,2020-01-21,1900-01-01 11:36:00,NaN,NaN,40.700580,-73.807750,POINT (-73.80775 40.70058),ARCHER AVENUE,NaN,NaN,...,Sedan,Sedan,NaN,NaN,NaN,Jan,Tuesday,11,ARCHER AVENUE,False
18966,2020-06-27,1900-01-01 15:15:00,BRONX,10451.0,40.815357,-73.928665,POINT (-73.928665 40.815357),NaN,NaN,350 GRAND CONCOURSE,...,Sedan,NaN,NaN,NaN,NaN,Jun,Saturday,15,NAN,False
34398,2020-04-11,1900-01-01 10:30:00,BROOKLYN,11223.0,40.601360,-73.976470,POINT (-73.97647 40.60136),WEST 4 STREET,AVENUE S,NaN,...,Sedan,NaN,NaN,NaN,NaN,Apr,Saturday,10,WEST 4 STREET,False
18674,2020-06-28,1900-01-01 08:10:00,BROOKLYN,11230.0,40.629543,-73.966080,POINT (-73.96608 40.629543),AVENUE H,CONEY ISLAND AVENUE,NaN,...,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,Jun,Sunday,8,AVENUE H,False
40130,2020-03-14,1900-01-01 15:56:00,NaN,NaN,40.696080,-73.969400,POINT (-73.9694 40.69608),PARK AVENUE,NaN,NaN,...,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,Mar,Saturday,15,PARK AVENUE,False

##### Export Result

In [73]:
df.to_csv("cleaned.csv", index=False)